version: '3.7'

services:
  idcops:
    build: .
    command: gunicorn idcops_proj.wsgi:application --workers 3 --bind :8000
    ports:
      - 8000:8000
    env_file:
      - ./config/.env.dev
    volumes:
      - .:/opt/django-idcops
